id: P2AAD78BA
initial_creation_type: ocr
source_metadata:
  volumes:
    03c7bcdc778940f58a4548144d1e9e22:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: མཉམ་ཉིད་གཞིའི་སྒྲོན་མ།
      total_pages: 1902
      volume_number: 26
